### ISSUE TITLE
RVAZ0JALM8PTGW8

### ISSUE THREAD

**Issue by haseebz** [bioinfoUGR/sRNAtoolbox#1]
I have been trying to generate the matrix of counts using sRNAbench and an error comes up:
There was an unexpected error. Please report it using the following code RVAZ0JALM8PTGW8

**Comment by sert23** [comment]
Dear @haseebz , thanks for your feedback.

I have checked this job that you mention and there should be no problem in generating a matrix, I wasn't able to replicate your issue. I have run a sRNAde job using the same conditions you already provided, please find it here.
https://arn.ugr.es/srnatoolbox/srnade/result?id=GZN3F6OUGP0WIQA

If this still didn't solve your issue, please let us know.

Best,
Ernesto
