### ISSUE TITLE
can't populate with Xenopus database

### ISSUE THREAD

**Issue by r0ark** [bioinfoUGR/sRNAtoolbox#11]
Hello! I am using the sRNAtoolbox docker and cannot seem to populate my database with Xenopus tropicalis. I am having no problem with loading data for other species, so I am curious if this is an X.tropicalis-specific issue. 

Thank you-

**Comment by bioinfoUGR** [comment]
Dear @r0ark, thanks for your feedback.

It was an issue specifically with _Xenopus tropicalis_ assembly which has been fixed now. Pleas, let us know if you can now download that assembly.

Best,
Cristina

**Comment by r0ark** [comment]
Thanks, Cristina! It is working now.
