### ISSUE TITLE
Docker Launch on M1 Mac

### ISSUE THREAD

**Issue by jackbrougher** [bioinfoUGR/sRNAtoolbox#2]
Hello,

Thank you for providing such a comprehensive toolbox. I am relatively new to Docker, and I'm trying to run the standalone version on my M1 Mac. I have docker installed, and receive no errors when I pass the run command for sRNAtoolbox. However, after I hit enter, nothing happens. I do have to pass an additional --platform linux/amd64 command since I'm on an M1.

 I'm assuming this is an error on my part, but any suggestions for getting the program to pull up? Apologies for the likely dumb question.

**Comment by cris12gm** [comment]
Dear @jackbrougher, thanks for your feedback.

Can you please put the commands you have launched so we can try to localize the problem?
It would be very helpful if you can send us the output of this command:
`docker ps -a`
which list all the docker located on your machine, to see if the sRNAtoolbox docker has been correctly installed.

Best,
Cristina

**Comment by jackbrougher** [comment]
Hello Cristina,

I realized it was a silly error on my part, and got it fixed. 

Is the webserver version of sRNAtoolbox down?

**Comment by cris12gm** [comment]
Dear @jackbrougher,

I'm glad to hear that you get the problem solved.

sRNAtoolbox webserver version is down due to technical problems beyond our control, it will be up as soon as possible. 

Best,
Cristina
